name: autism_screener
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  flutter_bloc: ^9.1.1
  firebase_core: ^3.13.1
  file_picker: ^10.1.9
  http: ^1.4.0
  path: ^1.9.1
  flutter_launcher_icons: ^0.14.3
  provider: ^6.1.5
  iconsax: ^0.0.8
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_gen_runner: ^5.10.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - .env
  fonts:
    - family: NotoSansArabic
      fonts:
        - asset: assets/font/NotoSansArabic-Regular.ttf
          weight: 400
